package models.insee

import play.api.libs.json.Json

case class ForeignCountry(
    inseeCode: Int,
    code: String,
    name: String,
    englishName: String,
    european: Boolean = false,
    transfer: Boolean = false
)

object ForeignCountry {
  val foreignCountries = List(
    ForeignCountry(99212, "AF", "Afghanistan", "Afghanistan"),
    ForeignCountry(99303, "ZA", "Afrique du Sud", "South Africa"),
    ForeignCountry(99125, "AL", "Albanie", "Albania"),
    ForeignCountry(99352, "DZ", "Algerie", "Algeria"),
    ForeignCountry(99109, "DE", "Allemagne", "Germany", european = true),
    ForeignCountry(99130, "AD", "Andorre", "Andorra", transfer = true),
    ForeignCountry(99395, "AO", "Angola", "Angola"),
    ForeignCountry(99441, "AG", "Antigua-et-Barbuda", "Antigua and Barbuda"),
    ForeignCountry(99201, "SA", "Arabie saoudite", "Saudi Arabia"),
    ForeignCountry(99415, "AR", "Argentine", "Argentina"),
    ForeignCountry(99252, "AM", "Arménie", "Armenia"),
    ForeignCountry(99501, "AU", "Australie", "Australia"),
    ForeignCountry(99110, "AT", "Autriche", "Austria", european = true),
    ForeignCountry(99253, "AZ", "Azerbaïdjan", "Azerbaijan"),
    ForeignCountry(99436, "BS", "Bahamas", "The Bahamas"),
    ForeignCountry(99249, "BH", "Bahreïn", "Bahrain"),
    ForeignCountry(99246, "BD", "Bangladesh", "Bangladesh"),
    ForeignCountry(99434, "BB", "Barbade", "Barbados"),
    ForeignCountry(99131, "BE", "Belgique", "Belgium", european = true),
    ForeignCountry(99429, "BZ", "Bélize", "Belize"),
    ForeignCountry(99327, "BJ", "Bénin", "Benin"),
    ForeignCountry(99214, "BT", "Bhoutan", "Bhutan"),
    ForeignCountry(99148, "BY", "Biélorussie", "Belarus"),
    ForeignCountry(99224, "MM", "Birmanie", "Myanmar"),
    ForeignCountry(99418, "BO", "Bolivie", "Bolivia"),
    ForeignCountry(99118, "BA", "Bosnie-Herzégovine", "Bosnia and Herzegovina"),
    ForeignCountry(99347, "BW", "Botswana", "Botswana"),
    ForeignCountry(99416, "BR", "Brésil", "Brazil"),
    ForeignCountry(99225, "BN", "Brunei", "Brunei"),
    ForeignCountry(99111, "BG", "Bulgarie", "Bulgaria", european = true),
    ForeignCountry(99331, "BF", "Burkina", "Burkina Faso"),
    ForeignCountry(99321, "BI", "Burundi", "Burundi"),
    ForeignCountry(99234, "KH", "Cambodge", "Cambodia"),
    ForeignCountry(99322, "CM", "Cameroun", "Cameroon"),
    ForeignCountry(99401, "CA", "Canada", "Canada"),
    ForeignCountry(99396, "CV", "Cap-Vert", "Cape Verde"),
    ForeignCountry(99323, "CF", "Centrafrique", "Central African Republic"),
    ForeignCountry(99417, "CL", "Chili", "Chile"),
    ForeignCountry(99216, "CN", "Chine", "China"),
    ForeignCountry(99254, "CY", "Chypre", "Cyprus", european = true),
    ForeignCountry(99419, "CO", "Colombie", "Colombia"),
    ForeignCountry(99397, "KM", "Comores", "Comoros"),
    ForeignCountry(99324, "CG", "Congo", "Congo"),
    ForeignCountry(99312, "CD", "République démocratique du Congo", "Democratic Republic of the Congo"),
    ForeignCountry(99502, "CK", "Îles Cook", "Cook Islands"),
    ForeignCountry(99238, "KP", "Corée du Nord", "North Korea"),
    ForeignCountry(99239, "KR", "Corée du Sud", "South Korea"),
    ForeignCountry(99406, "CR", "Costa Rica", "Costa Rica"),
    ForeignCountry(99326, "CI", "Côte d'Ivoire", "Côte d'Ivoire"),
    ForeignCountry(99119, "HR", "Croatie", "Croatia", european = true),
    ForeignCountry(99407, "CU", "Cuba", "Cuba"),
    ForeignCountry(99101, "DK", "Danemark", "Denmark", european = true),
    ForeignCountry(99399, "DJ", "Djibouti", "Djibouti"),
    ForeignCountry(99408, "DO", "République dominicaine", "Dominican Republic"),
    ForeignCountry(99438, "DM", "Dominique", "Dominica"),
    ForeignCountry(99301, "EG", "Égypte", "Egypt"),
    ForeignCountry(99247, "AE", "Émirats arabes unis", "United Arab Emirates"),
    ForeignCountry(99420, "EC", "Équateur", "Ecuador"),
    ForeignCountry(99317, "ER", "Érythrée", "Eritrea"),
    ForeignCountry(99134, "ES", "Espagne", "Spain", european = true),
    ForeignCountry(99106, "EE", "Estonie", "Estonia", european = true),
    ForeignCountry(99391, "SZ", "Eswatini", "Eswatini"),
    ForeignCountry(99404, "US", "États-Unis", "United States"),
    ForeignCountry(99315, "ET", "Éthiopie", "Ethiopia"),
    ForeignCountry(99508, "FJ", "Fidji", "Fiji"),
    ForeignCountry(99105, "FI", "Finlande", "Finland", european = true),
    ForeignCountry(99328, "GA", "Gabon", "Gabon"),
    ForeignCountry(99304, "GM", "Gambie", "Gambia"),
    ForeignCountry(99255, "GE", "Géorgie", "Georgia"),
    ForeignCountry(99329, "GH", "Ghana", "Ghana"),
    ForeignCountry(99126, "GR", "Grèce", "Greece", european = true),
    ForeignCountry(99435, "GD", "Grenade", "Grenada"),
    ForeignCountry(99409, "GT", "Guatémala", "Guatemala"),
    ForeignCountry(99330, "GN", "Guinée", "Guinea"),
    ForeignCountry(99314, "GQ", "Guinée équatoriale", "Equatorial Guinea"),
    ForeignCountry(99392, "GW", "Guinée-Bissao", "Guinea-Bissau"),
    ForeignCountry(99428, "GY", "Guyana", "Guyana"),
    ForeignCountry(99410, "HT", "Haïti", "Haiti"),
    ForeignCountry(99411, "HN", "Honduras", "Honduras"),
    ForeignCountry(99112, "HU", "Hongrie", "Hungary", european = true),
    ForeignCountry(99223, "IN", "Inde", "India"),
    ForeignCountry(99231, "ID", "Indonésie", "Indonesia"),
    ForeignCountry(99203, "IQ", "Irak", "Iraq"),
    ForeignCountry(99204, "IR", "Iran", "Iran"),
    ForeignCountry(99136, "IE", "Irlande", "Ireland", european = true),
    ForeignCountry(99102, "IS", "Islande", "Iceland", european = true),
    ForeignCountry(99207, "IL", "Israël", "Israel"),
    ForeignCountry(99127, "IT", "Italie", "Italy", european = true),
    ForeignCountry(99426, "JM", "Jamaïque", "Jamaica"),
    ForeignCountry(99217, "JP", "Japon", "Japan"),
    ForeignCountry(99222, "JO", "Jordanie", "Jordan"),
    ForeignCountry(99256, "KZ", "Kazakhstan", "Kazakhstan"),
    ForeignCountry(99332, "KE", "Kénya", "Kenya"),
    ForeignCountry(99257, "KG", "Kirghizstan", "Kyrgyzstan"),
    ForeignCountry(99513, "KI", "Kiribati", "Kiribati"),
    ForeignCountry(99157, "XK", "Kosovo", "Kosovo"),
    ForeignCountry(99240, "KW", "Koweït", "Kuwait"),
    ForeignCountry(99241, "LA", "Laos", "Laos"),
    ForeignCountry(99348, "LS", "Lésotho", "Lesotho"),
    ForeignCountry(99107, "LV", "Lettonie", "Latvia", european = true),
    ForeignCountry(99205, "LB", "Liban", "Lebanon"),
    ForeignCountry(99302, "LR", "Libéria", "Liberia"),
    ForeignCountry(99316, "LY", "Libye", "Libya"),
    ForeignCountry(99113, "LI", "Liechtenstein", "Liechtenstein"),
    ForeignCountry(99108, "LT", "Lituanie", "Lithuania", european = true),
    ForeignCountry(99137, "LU", "Luxembourg", "Luxembourg", european = true),
    ForeignCountry(99156, "MK", "Macédoine du Nord", "North Macedonia"),
    ForeignCountry(99333, "MG", "Madagascar", "Madagascar"),
    ForeignCountry(99227, "MY", "Malaisie", "Malaysia"),
    ForeignCountry(99334, "MW", "Malawi", "Malawi"),
    ForeignCountry(99229, "MV", "Maldives", "Maldives"),
    ForeignCountry(99335, "ML", "Mali", "Mali"),
    ForeignCountry(99144, "MT", "Malte", "Malta", european = true),
    ForeignCountry(99350, "MA", "Maroc", "Morocco"),
    ForeignCountry(99515, "MH", "Îles Marshall", "Marshall Islands"),
    ForeignCountry(99390, "MU", "Maurice", "Mauritius"),
    ForeignCountry(99336, "MR", "Mauritanie", "Mauritania"),
    ForeignCountry(99405, "MX", "Mexique", "Mexico"),
    ForeignCountry(99516, "FM", "Micronésie", "Micronesia"),
    ForeignCountry(99151, "MD", "Moldavie", "Moldova"),
    ForeignCountry(99138, "MC", "Monaco", "Monaco"),
    ForeignCountry(99242, "MN", "Mongolie", "Mongolia"),
    ForeignCountry(99120, "ME", "Monténégro", "Montenegro"),
    ForeignCountry(99393, "MZ", "Mozambique", "Mozambique"),
    ForeignCountry(99311, "NA", "Namibie", "Namibia"),
    ForeignCountry(99507, "NR", "Nauru", "Nauru"),
    ForeignCountry(99215, "NP", "Népal", "Nepal"),
    ForeignCountry(99412, "NI", "Nicaragua", "Nicaragua"),
    ForeignCountry(99337, "NE", "Niger", "Niger"),
    ForeignCountry(99338, "NG", "Nigéria", "Nigeria"),
    ForeignCountry(99502, "NU", "Niue", "Niue"),
    ForeignCountry(99103, "NO", "Norvège", "Norway", european = true),
    ForeignCountry(99502, "NZ", "Nouvelle-Zélande", "New Zealand"),
    ForeignCountry(99250, "OM", "Oman", "Oman"),
    ForeignCountry(99339, "UG", "Ouganda", "Uganda"),
    ForeignCountry(99258, "UZ", "Ouzbékistan", "Uzbekistan"),
    ForeignCountry(99213, "PK", "Pakistan", "Pakistan"),
    ForeignCountry(99517, "PW", "Palaos", "Palau"),
    ForeignCountry(99413, "PA", "Panama", "Panama"),
    ForeignCountry(99510, "PG", "Papouasie-Nouvelle-Guinée", "Papua New Guinea"),
    ForeignCountry(99421, "PY", "Paraguay", "Paraguay"),
    ForeignCountry(99135, "NL", "Pays-Bas", "Netherlands", european = true),
    ForeignCountry(99422, "PE", "Pérou", "Peru"),
    ForeignCountry(99220, "PH", "Philippines", "Philippines"),
    ForeignCountry(99122, "PL", "Pologne", "Poland", european = true),
    ForeignCountry(99139, "PT", "Portugal", "Portugal", european = true),
    ForeignCountry(99248, "QA", "Qatar", "Qatar"),
    ForeignCountry(99114, "RO", "Roumanie", "Romania", european = true),
    ForeignCountry(99132, "GB", "Royaume-Uni", "United Kingdom"),
    ForeignCountry(99123, "RU", "Russie", "Russia"),
    ForeignCountry(99340, "RW", "Rwanda", "Rwanda"),
    ForeignCountry(99442, "KN", "Saint-Christophe-et-Niévès", "Saint Kitts and Nevis"),
    ForeignCountry(99439, "LC", "Sainte-Lucie", "Saint Lucia"),
    ForeignCountry(99128, "SM", "Saint-Marin", "San Marino"),
    ForeignCountry(99440, "VC", "Saint-Vincent-et-les-Grenadines", "Saint Vincent and the Grenadines"),
    ForeignCountry(99512, "SB", "Salomon", "Solomon Islands"),
    ForeignCountry(99414, "SV", "Salvador", "El Salvador"),
    ForeignCountry(99506, "WS", "Samoa", "Samoa"),
    ForeignCountry(99394, "ST", "Sao Tomé-et-Principe", "Sao Tome and Principe"),
    ForeignCountry(99341, "SN", "Sénégal", "Senegal"),
    ForeignCountry(99121, "RS", "Serbie", "Serbia"),
    ForeignCountry(99398, "SC", "Seychelles", "Seychelles"),
    ForeignCountry(99342, "SL", "Sierra Leone", "Sierra Leone"),
    ForeignCountry(99226, "SG", "Singapour", "Singapore"),
    ForeignCountry(99117, "SK", "Slovaquie", "Slovakia", european = true),
    ForeignCountry(99145, "SI", "Slovénie", "Slovenia", european = true),
    ForeignCountry(99318, "SO", "Somalie", "Somalia"),
    ForeignCountry(99343, "SD", "Soudan", "Sudan"),
    ForeignCountry(99349, "SS", "Soudan du Sud", "South Sudan"),
    ForeignCountry(99235, "LK", "Sri Lanka", "Sri Lanka"),
    ForeignCountry(99104, "SE", "Suède", "Sweden", european = true),
    ForeignCountry(99140, "CH", "Suisse", "Switzerland", transfer = true),
    ForeignCountry(99437, "SR", "Suriname", "Suriname"),
    ForeignCountry(99206, "SY", "Syrie", "Syria"),
    ForeignCountry(99259, "TJ", "Tadjikistan", "Tajikistan"),
    ForeignCountry(99309, "TZ", "Tanzanie", "Tanzania"),
    ForeignCountry(99344, "TD", "Tchad", "Chad"),
    ForeignCountry(99116, "CZ", "Tchéquie", "Czech Republic", european = true),
    ForeignCountry(99219, "TH", "Thaïlande", "Thailand"),
    ForeignCountry(99262, "TL", "Timor oriental", "East Timor"),
    ForeignCountry(99345, "TG", "Togo", "Togo"),
    ForeignCountry(99509, "TO", "Tonga", "Tonga"),
    ForeignCountry(99433, "TT", "Trinité-et-Tobago", "Trinidad and Tobago"),
    ForeignCountry(99351, "TN", "Tunisie", "Tunisia"),
    ForeignCountry(99260, "TM", "Turkménistan", "Turkmenistan"),
    ForeignCountry(99208, "TR", "Turquie", "Turkey"),
    ForeignCountry(99511, "TV", "Tuvalu", "Tuvalu"),
    ForeignCountry(99155, "UA", "Ukraine", "Ukraine"),
    ForeignCountry(99423, "UY", "Uruguay", "Uruguay"),
    ForeignCountry(99514, "VU", "Vanuatu", "Vanuatu"),
    ForeignCountry(99129, "VA", "Vatican", "Vatican City"),
    ForeignCountry(99424, "VE", "Vénézuéla", "Venezuela"),
    ForeignCountry(99243, "VN", "Vietnam", "Vietnam"),
    ForeignCountry(99251, "YE", "Yémen", "Yemen"),
    ForeignCountry(99346, "ZM", "Zambie", "Zambia"),
    ForeignCountry(99310, "ZW", "Zimbabwé", "Zimbabwe"),
    ForeignCountry(99101, "FO", "Îles Féroé", "Faroe Islands"),
    ForeignCountry(99103, "SJ", "Svalbard et Île Jan Mayen", "Svalbard and Jan Mayen"),
    ForeignCountry(99103, "BV", "Île Bouvet", "Bouvet Island"),
    ForeignCountry(99132, "JE", "Jersey", "Jersey"),
    ForeignCountry(99132, "IM", "Île Man", "Isle of Man"),
    ForeignCountry(99132, "GG", "Guernsey", "Bailiwick of Guernsey"),
    ForeignCountry(99133, "GI", "Gibraltar", "Gibraltar"),
    ForeignCountry(99135, "AW", "Aruba", "Aruba"),
    ForeignCountry(99230, "HK", "Hong-Kong", "Hong Kong"),
    ForeignCountry(99232, "MO", "Macao", "Macau"),
    ForeignCountry(99236, "TW", "Taiwan", "Taiwan"),
    ForeignCountry(99261, "PS", "État de Palestine", "State of Palestine"),
    ForeignCountry(
      99306,
      "SH",
      "Sainte-Hélène, Ascension et Tristan da Cunha",
      "Saint Helena, Ascension and Tristan da Cunha"
    ),
    ForeignCountry(99308, "IO", "Territoire britannique de l'océan Indien", "British Indian Ocean Territory"),
    ForeignCountry(99389, "EH", "Sahara occidental", "Western Sahara"),
    ForeignCountry(99425, "VG", "Îles Vierges britanniques", "British Virgin Islands"),
    ForeignCountry(99425, "TC", "Îles Turques-et-Caïques", "Turks and Caicos Islands"),
    ForeignCountry(99425, "MS", "Montserrat", "Montserrat"),
    ForeignCountry(99425, "KY", "Îles Caïmans", "Cayman Islands"),
    ForeignCountry(99425, "BM", "Bermudes", "Bermuda"),
    ForeignCountry(99425, "AI", "Anguilla", "Anguilla"),
    ForeignCountry(
      99427,
      "GS",
      "Géorgie du Sud-et-les îles Sandwich du Sud",
      "South Georgia and the South Sandwich Islands"
    ),
    ForeignCountry(99427, "FK", "Îles Malouines ou Falkland", "Falkland Islands"),
    ForeignCountry(99430, "GL", "Groenland", "Greenland"),
    ForeignCountry(99431, "AN", "Antilles néerlandaises", "Netherlands Antilles"),
    ForeignCountry(99432, "VI", "Îles Vierges des États-Unis", "United States Virgin Islands"),
    ForeignCountry(99432, "PR", "Porto Rico", "Puerto Rico"),
    ForeignCountry(99443, "BQ", "Bonaire, Saint Eustache et Saba", "Bonaire, Sint Eustatius and Saba"),
    ForeignCountry(99444, "CW", "Curaçao", "Curaçao"),
    ForeignCountry(99445, "SX", "Saint-Martin (royaume des Pays-Bas)", "Sint Maarten (Dutch part)"),
    ForeignCountry(99501, "NF", "Île Norfolk", "Norfolk Island"),
    ForeignCountry(99501, "HM", "Îles Heard-et-MacDonald", "Heard Island and McDonald Islands"),
    ForeignCountry(99501, "CX", "Île Christmas", "Christmas Island"),
    ForeignCountry(99501, "CC", "Îles Cocos", "Cocos (Keeling) Islands"),
    ForeignCountry(99502, "TK", "Tokelau", "Tokelau"),
    ForeignCountry(99503, "PN", "Îles Pitcairn", "Pitcairn Islands"),
    ForeignCountry(99505, "MP", "Îles Mariannes du Nord", "Northern Mariana Islands"),
    ForeignCountry(99505, "GU", "Guam", "Guam"),
    ForeignCountry(99505, "AS", "Samoa américaines", "American Samoa")
  )

  implicit val writes = Json.writes[ForeignCountry]
}
